name: open_seed
description: "OpenSeed: towards a open-source seed image analysis ecosystem."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.4.1
  change_case: ^2.2.0
  custom_refresh_indicator: ^4.0.1
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  envied: ^1.3.1
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  flutter_inappwebview: ^6.2.0-beta.2
  geolocator: ^14.0.2
  hydrated_bloc: ^10.1.1
  image_picker: ^1.2.1
  intl: ^0.20.2
  iplant_api:
    path: packages/iplant_api
  json_annotation: ^4.9.0
  logger: ^2.6.2
  material_symbols_icons: ^4.2874.0
  mnn:
    git:
      url: https://github.com/rainyl/mnn.dart.git
      ref: 73d3b16
  package_info_plus: ^8.3.1
  path_provider: ^2.1.5
  pro_image_editor: ^11.12.2
  sqlite3: ^3.0.1
  url_launcher: ^6.3.2
  waterfall_flow: ^3.1.1
  weather: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_lint: ^0.2.0-dev.4
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  # intl_translation: ^0.20.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/icons/logo.png
    - assets/models/
    - assets/class_desc.txt
    - assets/openseed.db

hooks:
  user_defines:
    sqlite3:
      source: sqlite3mc
    mnn:
      options:
        build_local: true
      defines:
        common:
          MNN_SUPPORT_BF16: ON
          MNN_BUILD_OPENCV: OFF
          MNN_LOW_MEMORY: OFF
        macos:
          MNN_METAL: ON
        android:
          MNN_OPENCL: ON
          MNN_OPENGL: OFF
          MNN_VULKAN: OFF
          MNN_VULKAN_IMAGE: OFF
          MNN_ARM82: ON
          MNN_USE_SYSTEM_LIB: OFF
